listener 1883 0.0.0.0 # This tells Mosquitto to open port 1883 (the standard port for MQTT traffic) and listen for incoming messages here.
# 0.0.0.0 is a networking rule that means "listen to connections coming from anywhere." Without this, Mosquitto would only listen to my laptop itself (localhost)
allow_anonymous true
# allow_anonymous true: This permits devices to connect and send messages without a username or password.