# Read metrics from MQTT Topic
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["env/microclimate"]
  data_format = "json"
  name_override = "microclimate"

# Send metrics to InfluxDB
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "my-super-secret-permanent-token-12345"
  organization = "env_data"
  bucket = "microclimate"
